
builds:
  - id: xsops
    binary: xsops
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./main.go
    hooks:
      pre: go mod tidy
      post: go mod tidy

checksum:
  # You can change the name of the checksums file.
  #
  # Default: '{{ .ProjectName }}_{{ .Version }}_checksums.txt', or,
  #   when split is set: '{{ .ArtifactName }}.{{ .Algorithm }}'.
  # Templates: allowed.
  name_template: "{{ .ProjectName }}-checksums.txt"

archives:
  - id: xsops
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
    format_overrides:
      - goos: windows
        formats: [zip, tar.gz]

    files:
      - LICENSE.md
      - README.md

nfpms:
  - id: xsops
    description:  |
      xsops is a command-line tool for managing environment variables and executing commands with those variables set."
    homepage: "https://github.com/hyprxlabs/hx-env"
    file_name_template: "{{ .PackageName }}-{{ .Os }}-{{ .Arch}}-{{ .Version }}"
    maintainer: "Hyprxdev <180069990+hyprxdev@users.noreply.github.com>"
    license: "MIT"
    formats:
      - deb
      - rpm
      - archlinux
      - apk

chocolateys:
  - name: xsops
    description: |
      A cross-platform cli using sops and json as a local secret store.

      The `xsops` command allows you to manage secrets stored in JSON files using the sops tool.

      The secrets can be easily retrieved, set, and removed from the command line.
    package_source_url: "https://github.com/hyprxlabs/xsops"
    title: "xsops"
    project_url: "https://github.com/hyprxlabs/xsops"
    copyright: "Copyright © 2025 hyprxdev hyprxlabs"
    require_license_acceptance: false
    icon_url: "https://raw.githubusercontent.com/hyprxlabs/dotnet/refs/heads/main/eng/assets/hyprx_logo_256.png"
    authors: "Hyprxdev <180069990+hyprxdev@users.noreply.github.com>"
    tags: "xsops sops"
    summary: "xsops is a crossplatform cli app for sops and json as a local secret store."
    release_notes: "https://github.com/foo/bar/releases/tag/v{{ .Version }}"
    skip_publish: true

    